site_name: Aethoce's Blog
site_description: Aethoce's Blog


nav:
  - Blog: blog/index.md
  - 标签: blog/tags.md
  - 关于我: blog/about.md
theme:
  name: material
  language: zh
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.footer
    - content.code.copy
    - toc.follow
    - toc.integrate
  
plugins:
  - optimize
  - tags:
      tags_file: blog/tags.md
  - blog:
      archive_toc: true
      categories_toc: true
      blog_toc: true
      pagination_per_page: 25
      categories: true

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

extra:
  analytics:
    provider: google
    property: G-67XGNSFM2J
